### ISSUE TITLE
Prophet package

### ISSUE THREAD

**Issue by mariabnd** [HIDDA/forecasting#1]
Hi @bastistician 

You might be interested in knowing that the prophet package was [archived on 23rd April](https://cran.r-project.org/web/packages/prophet/index.html) and this might give users a `package ‘prophet’ is not available` error when installing the HIDDA.forecasting package

**Comment by bastistician** [comment]
Thanks for letting me know. I guess **prophet** will be back on CRAN soon (https://github.com/facebook/prophet/issues/1448).
Meanwhile, you could install **prophet** from GitHub as described [here](https://github.com/facebook/prophet#installation-in-r).

**Comment by mariabnd** [comment]
It seems to be back now
